name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image 
        run: sudo docker pull kshitijg/cicd-pipeline:latest
      - name: Delete Old Docker 
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: Run Docker Container 
        run: sudo docker run -d -p 8080:3400 --name cicd-pipeline-container kshitijg/cicd-pipeline